# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joqFpJ2Drqi-Ir73kXB0MPs1ZdXgnPU6
"""

n,k =map(int,input().split())
need=list(map(int,input().split()))
have=list(map(int,input().split()))
st=0
en =sum(have) +k
mx =0
while(st<=en):
    mid =st+(en-st)//2 
    dif =0
    for i  in range(n):
        k1=mid*need[i]
        if have[i]>k1:
            dif+=0 
        else:
            dif+=k1-have[i]
    if dif<=k:
        if mid>mx:
            mx=mid
        st=mid+1 
    elif dif>k:
        en=mid-1 
print(mx)