# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joqFpJ2Drqi-Ir73kXB0MPs1ZdXgnPU6
"""

for _ in range(int(input())):
    n,h =map(int,input().split())
    l =list(map(int,input().split()))
    st =0
    en =h
    mn=10**19
    while(st<=en):
        c=0
        mid =(st+en)//2
        for i in range(n):
            if i!=n-1:
                k =min(l[i]-1+mid,l[i+1]-1)
                c+=k-(l[i]-1)
            else:
                c+=mid
        if c>h:
            if mid <mn:
                mn =mid
            en =mid-1 
            
        elif c<h:
            st=mid+1 
        else:
            if mid <mn:
                mn =mid
            
            en =mid-1
            
    print(mn)